version: '3'

services:
  fastapi:
    build: fastapi/
    ports: 
      - 8008:8000
    networks:
      - deploy_network
    container_name: segmentation-fastapi_backend

  streamlit:
    build: streamlit/
    depends_on:
      - fastapi
    ports: 
        - 8507:8501
    networks:
      - deploy_network
    container_name: segmentation-streamlit_frontend

networks:
  deploy_network:
    driver: bridge